### ISSUE TITLE
Find possible memory leak in Smeedee

### ISSUE THREAD

**Issue by benteca** [Smeedee/Smeedee#65]

**Comment by khiim** [comment]
There seems to be an issue with the ViewModelBase from TinyMVVM creating new Ninject.StandardKernel for each object, and also it binds all view models to the ninject kernel as statics. This could possibly be the reason for viewmodels never being garbage collected, and the fact that there are thousands of Ninject.StandardKernels in memory after running smeedee for some time.

tl;dr: bug in TinyMVVM, making lots of Ninject.StandardKernels, and binding all viewmodels to kernel.

**Comment by khiim** [comment]
The major reason for memory leaks in Smeedee is the fact that it uses Ninject incorrect, and instantiates a new Ninject.StandardKernel for every object of classes derived from ViewModelBase (from TinyMVVM). Fixing this issue is out of the scope of SoC2011 Sprint3, but as the leak has been found, this issue is closed, and a new issue for fixing it will be created.
